### ISSUE TITLE
希望添加arm64支持

### ISSUE THREAD

**Issue by ldxw** [2233466866/lnmp#3]
希望大佬出个arm64的。。。。

**Comment by 2233466866** [comment]
arm64是一种硬件架构，与镜像无关；你应该是说想要amd64版本的，本镜像原本就是amd64版本，支持arm64架构的处理器。

**Comment by 2233466866** [comment]
### ARM64版正在测试
1. 相关代码地址如下
     1. https://github.com/2233466866/lnmp/tree/arm64
     1. https://github.com/2233466866/lnmp/releases/tag/1.9-arm64
1. 测试通过后这样获取它
   ```
   docker pull 2233466866/lnmp:1.9-arm64
   ```

**Comment by ldxw** [comment]
@2233466866  奇怪了。。。。

**Comment by SoraKasvgano** [comment]
同，希望增加armv7 v8 支持

**Comment by SoraKasvgano** [comment]
军哥的lnmp脚本在s805 armv7 n1 s905 armv8跑的挺好的emmm按理说也能docker跑emmm等待路过的大神增加

**Comment by 2233466866** [comment]
> 军哥的lnmp脚本在s805 armv7 n1 s905 armv8跑的挺好的emmm按理说也能docker跑emmm等待路过的大神增加
我想想办法

**Comment by 2233466866** [comment]
> @2233466866 奇怪了。。。。

好像有办法了
https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by 2233466866** [comment]
`name: BuildImage

on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2

      - name: step2
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: step3
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: step4
      run: |
        docker buildx build --tag 2233466866/lnmp:test --platform linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 .`

**Comment by 2233466866** [comment]
```
name: BuildImage

on:
  push:
    branches: test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2

      - name: step2
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v3

      - name: step3
        if: success() && github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: step4
      run: |
        docker buildx build --tag 2233466866/lnmp:test --platform linux/386,linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v8 .
```
